name: Compile the self-driving-car controller / supervisor

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Compile the self-driving-car controller / supervisor
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Compile controller.ino
        uses: ArminJo/arduino-test-compile@v3
